title: ST542 - Consulting Project
description: The Impact of Plant Spacing and Nitrogen Levels on Pumpkin Yield
show_downloads: true
google_analytics: UA-44627132-6
theme: jekyll-theme-leap-day
#Custom URLs can be created using the below section for the GitHub page references used in html layout
#Keep 1 space indent of declared URLs following the "github:" line
#github:
# zip_url: https://github.com/bsugg/PumpkinProject/tree/main/CleanData/download.zip
