title: Pumpkin Yield Study
description: Pumpkin Yield Study
show_downloads: true
google_analytics: UA-44627132-6
theme: jekyll-theme-leap-day

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: bjsugg@ncsu.edu
  facebook:
  flickr:
  github: bsugg/bsugg.github.io
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: 
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/
