---
title: "ST542 - Consulting Project"
author: "Brian Sugg & Chengxi Zou"
date: "1/26/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(formatR)
library(dplyr)
library(readxl)
library(ggplot2)
library(writexl)
knitr::opts_chunk$set(echo=TRUE,tidy.opts=list(width.cutoff=70),tidy=TRUE)
```

# Import Data  

```{r readExcel}
# Read sheet with WEIGHTS, transform from wide to tall, remove NA records
spacingWeight <- read_excel(path="pumpkin_play.xlsx", sheet="Spacing Weights (lbs)")
spacingWeight <- gather(spacingWeight,key="Pumpkin",value="Weight",8:55)
spacingWeight <- subset(spacingWeight,!is.na(Weight))
# Rename columns
names(spacingWeight) <- c("plot","treatment","rep","standCount","standCountIdeal","spacingDim","greenPumpkins","pumpkinNum","weight")
# Create unique identifier for each pumpkin
spacingWeight <- mutate(spacingWeight,pumpkinID=paste(plot,"-",pumpkinNum))

# Read sheet with LENGTHS, transform from wide to tall, remove NA records
spacingLength <- read_excel(path="pumpkin_play.xlsx", sheet="Spacing Lengths (inches)")
spacingLength <- gather(spacingLength,key="Pumpkin",value="Length",8:55)
spacingLength <- subset(spacingLength,!is.na(Length))
# Rename columns
names(spacingLength) <- c("plot","treatment","rep","standCount","standCountIdeal","spacingDim","greenPumpkins","pumpkinNum","length")
# Create unique identifier for each pumpkin
spacingLength <- mutate(spacingLength,pumpkinID=paste(plot,"-",pumpkinNum))

# Read sheet with DIAMETERS, transform from wide to tall, remove NA records
spacingDiameter <- read_excel(path="pumpkin_play.xlsx", sheet="Spacing Diameters (inches)")
spacingDiameter <- gather(spacingDiameter,key="Pumpkin",value="Diameter",8:55)
spacingDiameter <- subset(spacingDiameter,!is.na(Diameter))
# Rename columns
names(spacingDiameter) <- c("plot","treatment","rep","standCount","standCountIdeal","spacingDim","greenPumpkins","pumpkinNum","diameter")
# Create unique identifier for each pumpkin
spacingDiameter <- mutate(spacingDiameter,pumpkinID=paste(plot,"-",pumpkinNum))
```  

# Transform Data  

```{r transformData}
# Join all spacing metrics in one raw table for quality checks
spacingDataRaw <- inner_join(spacingWeight,spacingLength)
spacingDataRaw <- inner_join(spacingDataRaw,spacingDiameter)

# Create clean table for further transformations
spacingData <- as_tibble(spacingDataRaw)

# Format variables
spacingData$plot <- as.factor(spacingData$plot)
spacingData$treatment <- as.factor(spacingData$treatment)
spacingData$rep <- as.factor(spacingData$rep)
spacingData$pumpkinNum <- as.numeric(spacingData$pumpkinNum)

# Create variable for pumpkin color, populate based on conditional statement, and format
spacingData <- mutate(spacingData,color="unknown")
for (i in 1:nrow(spacingData)) {
  spacingData[i,13] <- if_else(spacingData[i,8] %in% sapply(strsplit(as.character(spacingData[i,7]),split=", "),function(x) as.numeric(x)),
                                 "Green",
                                 "Orange")
}
spacingData$color <- as.factor(spacingData$color)

# Create variable for spacing area and transform spacing variables factors
spacingData <- mutate(spacingData,spacingArea=sapply(strsplit(as.character(spacingDim),split=" x "),function(x) prod(as.numeric(x))))
spacingData$spacingArea <- as.factor(spacingData$spacingArea)
spacingData$spacingDim <- as.factor(spacingData$spacingDim)
spacingData$length <- as.numeric(spacingData$length)

# Create variable for realized ideal stand count percentage
spacingData <- mutate(spacingData,standCountIdealPct=standCount/standCountIdeal)

# Arrange columns for presentation of final table for spacing data
spacingData <- select(spacingData,c(10,1,3,2,8,6,14,4,5,15,13,9,11,12))

# Provide structure of transformed variables with data preview
str(spacingData)
spacingData

# Export R data object to Excel for client review
write_xlsx(spacingData,"spacingData.xlsx")
```

# Explore Data  

```{r exploreData}
# Scatter plot of weight vs length
plot(spacingData$length,spacingData$weight,
     xlab="Diameter (in)",
     ylab="Weight (lbs)")

# Scatter plot of weight vs diameter
plot(spacingData$diameter,spacingData$weight,
     xlab="Length (in)",
     ylab="Weight (lbs)")

# Scatter plot of diameter vs length
plot(spacingData$length,spacingData$diameter,
     xlab="Length (in)",
     ylab="Diameter (in)")

# Boxplot by spacing dimension
ggplot(spacingData, aes(x=spacingDim, y=weight, fill=spacingDim)) +
    geom_boxplot(varwidth = TRUE, alpha=0.2) +
    theme(legend.position="none")

# Boxplot by spacing area
ggplot(spacingData, aes(x=spacingArea, y=weight, fill=spacingArea)) +
    geom_boxplot(varwidth = TRUE, alpha=0.2) +
    theme(legend.position="none")
```


